
<div class="btn-group pull-right" >
  <button class="btn btn-large btn-success">Do Something.</button>
  <button class="btn btn-large btn-success dropdown-toggle" data-toggle="dropdown">
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
	<li /><a href="new_list.php">Add A New Item</a>
	<li /><a href="index.php">View/Edit List</a>
	<li /><a href="logout.php">Logout</a>
  </ul>
  </div>
