<div id="space"></div>
<hr>

      <footer>
       <h5>By Brandan Majeske &bull; BDF1302 &bull; Full Sail University</h5>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="js/jquery-1.8.2.min.js"></script>
    <script src="js/bootstrap.js"></script>
  </body>
</html>
