<h3>Please log in with your username and password below.</h3>

<form action="?" method="POST">
<label for="username">Username:</label>
	<input type="text" name="username" id="username" maxlength="50" size="20"/><br />

<label for="password">Password:</label>
	<input type="password" name="password" id="password" maxlength="50" size="20" /><br />
<input type="submit" class="btn btn-primary" value="Login" />
</form>

<p>Not a registered user? <a href="register.php">Sign Up</a> today!</p>
